server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv:mongodb+srv://rohitarame8:Z1Ow8hMGHxnWTR9o@cluster22.pnzm7sy.mongodb.net/?appName=Cluster22}
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}
  expiration: 86400000 # 24 hours

logging:
  level:
    in.cloudblitz.auth: DEBUG
